from python:2.7

RUN apt-get update
RUN apt-get -y install git
RUN mkdir -p /senpy-plugins

#RUN apt-get -y install python-numpy
#RUN apt-get -y install python-scipy
#RUN apt-get -y install python-sklearn
RUN apt-get -y install python-gevent
RUN apt-get -y install libopenblas-dev
RUN apt-get -y install gfortran
RUN apt-get -y install libxml2-dev libxslt1-dev python-dev

RUN pip install --upgrade pip

RUN pip install numpy==1.8.2
RUN pip install scipy==0.14.0
RUN pip install scikit-learn==0.14.1
RUN pip install nltk==3.0.5
RUN pip install lxml==3.4.2
RUN pip install textblob
RUN pip install pattern
RUN pip install pandas
RUN pip install senpy


RUN python -m nltk.downloader stopwords
RUN python -m nltk.downloader punkt
RUN python -m nltk.downloader maxent_treebank_pos_tagger
RUN python -m nltk.downloader wordnet
RUN python -m nltk.downloader omw
